---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: eng
  annotations:
    backstage.io/view-url: https://github.com/Apicurio/backstage/blob/main/apicurio/org/groups.yaml
    backstage.io/edit-url: https://github.com/Apicurio/backstage/edit/main/apicurio/org/groups.yaml
spec:
  type: team
  children: [prod,frontend]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: prod
  annotations:
    backstage.io/view-url: https://github.com/Apicurio/backstage/blob/main/apicurio/org/groups.yaml
    backstage.io/edit-url: https://github.com/Apicurio/backstage/edit/main/apicurio/org/groups.yaml
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: frontend
  annotations:
    backstage.io/view-url: https://github.com/Apicurio/backstage/blob/main/apicurio/org/groups.yaml
    backstage.io/edit-url: https://github.com/Apicurio/backstage/edit/main/apicurio/org/groups.yaml
spec:
  type: team
  children: []



---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: qe
  annotations:
    backstage.io/view-url: https://github.com/Apicurio/backstage/blob/main/apicurio/org/groups.yaml
    backstage.io/edit-url: https://github.com/Apicurio/backstage/edit/main/apicurio/org/groups.yaml
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: docs
  annotations:
    backstage.io/view-url: https://github.com/Apicurio/backstage/blob/main/apicurio/org/groups.yaml
    backstage.io/edit-url: https://github.com/Apicurio/backstage/edit/main/apicurio/org/groups.yaml
spec:
  type: team
  children: []
