app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: ${APP_CONFIG_APP}

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: ${APP_CONFIG_BACKEND}
  listen:
    port: 7007
    # The following host directive binds to all IPv4 interfaces when its value
    # is "0.0.0.0". This is the most permissive setting. The right value depends
    # on your specific deployment. If you remove the host line entirely, the
    # backend will bind on the interface that corresponds to the backend.baseUrl
    # hostname.
    host: 0.0.0.0

  # config options: https://node-postgres.com/api/client
  database:
  
    # DEVELOPMENT MODE:
    # client: better-sqlite3
    # connection: ':memory:'

    # PRODUCTION MODE:
    client: pg
    pluginDivisionMode: schema # https://backstage.io/docs/tutorials/switching-sqlite-postgres#using-a-single-database
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: backstage
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

  reading:
    allow:
      # LOCAL DEV
      - host: apicurio-registry-mt-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud
      # LIVE CLUSTER
      - host: apicurio-registry-mt:8080
      
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers: 
    github:
        development:
          clientId: ${AUTH_GITHUB_CLIENT_ID}
          clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
          
catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/software-catalog-overview#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ./apicurio/registry.yaml
    - type: file
      target: ./apicurio/demo.yaml
    # Local example template
    - type: file
      target: ./apicurio/sw/registry.yaml
      rules:
      - allow: [Component, System, API, Resource, Location]
    - type: file
      target: ./apicurio/sw/studio.yaml
      rules:
      - allow: [Component, System, API, Resource, Location]
    - type: file
      target: ./apicurio/sw/website.yaml
      rules:
      - allow: [Component, System, API, Resource, Location]
    - type: file
      target: ./apicurio/sw/datamodels.yaml
      rules:
      - allow: [Component, System, API, Resource, Location]
    - type: file
      target: ./apicurio/sw/apicurito.yaml
      rules:
      - allow: [Component, System, API, Resource, Location]
    - type: file
      target: ./apicurio/sw/systems/upstream.yaml
      rules:
      - allow: [Component, System, API, Resource, Location]
    - type: file
      target: ./apicurio/sw/systems/downstream.yaml
      rules:
      - allow: [Component, System, API, Resource, Location]

    - type: file
      target: ./apicurio/demo.yaml
    - type: file
      target: ./apicurio/org/users.yaml
      rules:
        - allow: [User]
    - type: file
      target: ./apicurio/org/groups.yaml
      rules:
        - allow: [Group]

    - type: file
      target: ./apicurio/registry.yaml
    - type: file
      target: ./apicurio/demo.yaml
    - type: file
      target: ./catalog-info.yaml
  providers:
    apicurio:
      url: ${APICURIO_ENDPOINT}    