version: '3.8'
volumes:
  postgres-db:
    driver: local
services:
  apicurio:
    image: apicurio/apicurio-registry-mem:latest-snapshot
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backstage
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - 5432:5432
  backstage:
    image: backstage
    depends_on:
      - db
      - apicurio
    ports:
      - 7007:7007
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: postgres
      APP_CONFIG_BACKEND: backstage:7007
      APP_CONFIG_APP: backstage:7007
      APICURIO_ENDPOINT: http://localhost:8080
      APP_CONFIG_catalog_providers_apicurio_url: http://apicurio:8080
      APP_CONFIG_backend_reading_allow-host: localhost:8080
    links:
      - db
