name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: yarn.lock  
      - name: Build web app
        run: yarn && yarn tsc && yarn build    
      - name: Build OCI image
        run: docker build .                
   